version: '3'

services:
  spark-master: # Spark Master
    container_name: spark-master
    image: docker.io/bitnami/spark:3.2.1
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - type: bind # For disable log only
        source: ./conf/log4j.properties # For disable log only
        target: /opt/bitnami/spark/conf/log4j.properties # For disable log only
      - ".:/TRAVIST_Spark:rw" # Name volume for container to access the local root of this project
    networks:
      - spark
  spark-worker: # Spark Worker
    container_name: spark-worker
    image: docker.io/bitnami/spark:3.2.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - type: bind # For disable log only
        source: ./conf/log4j.properties # For disable log only
        target: /opt/bitnami/spark/conf/log4j.properties # For disable log only
    networks:
      - spark
    depends_on:
      - spark

networks:
  spark:
    driver: bridge