name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'temurin'
    - name: Run tests
      run: sbt test
